### PR TITLE
Fixed #18 | Guard the input fields that return optional values

### LINKED ISSUE #18: Guard input field values
We should `guard` the input field values to prevent having to worry about nil values being passed to the model. 

[https://thatthinginswift.com/guard-statement-swift/](https://thatthinginswift.com/guard-statement-swift/)

Currently crashes the app.

### PR DESCRIPTION
**Pull request by TetHat**

### CODE REVIEW

File: Pump-Tracker/SkuDetailViewController.swift [hunk 1]
```diff
@@ -92,20 +92,66 @@ class SkuDetailViewController: UITableViewController {
...
+            
+            /// Add the cancel button to the alert controller
+            ac.addAction(UIAlertAction(title: "OK", style: .cancel))
+            
+            /// Present the alert controller and animate it
+            self.present(ac, animated: true)
+            return
+        }
+        
+        /// Guard amount field since grabbing the title returns optional value so we can't pass empty values to model
```
Comment (beetdemguise) [inline Pump-Tracker/SkuDetailViewController.swift]: Copy-paste comment?
